name: blurred_overlay
description: A lightweight Flutter package to show blurred dialogs and bottom sheets with shadow and radius.
version: 1.0.2
homepage: https://github.com/Ebrahim683/blurred_overlay
repository: https://github.com/Ebrahim683/blurred_overlay
issue_tracker: https://github.com/Ebrahim683/blurred_overlay/issues
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
