name: blurred_overlay
description: A Flutter package to display blurred dialogs and modal bottom sheets with custom shadows, radius, and styling.
version: 1.0.0
homepage: https://github.com/Ebrahim683/blurred_overlay
repository: https://github.com/Ebrahim683/blurred_overlay
issue_tracker: https://github.com/Ebrahim683/blurred_overlay/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
